// Copyright 2019-2021 The Khronos Group, Inc.
// SPDX-License-Identifier: CC-BY-4.0

ifndef::chapters[:chapters: ../]

[[VK_KHR_image_format_list]]
= VK_KHR_image_format_list

[NOTE]
====
Promoted to core in Vulkan 1.2
====

On some implementations, setting the `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` on `VkImage` creation can cause access to that `VkImage` to perform worse than an equivalent `VkImage` created without `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` because the implementation does not know what `VkImageView` formats will be paired with the `VkImage`. This may force the implementation to disable (`VkImageView`) format-specific optimizations such as lossless image compression. If the `VkImageFormatListCreateInfo` struct used to explicitly list the `VkImageView` formats the `VkImage` may be paired with, the implementation may be able to enable format-specific optimization in additional cases.

If the application is not using the `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` to create images, then there is no need to be concerned with this extension.
