language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot --allow-dupe chapters/*.md chapters/extensions/*.md --white-list https://www.youtube.com/
notifications:
  email: false
