version = 1

[[annotations]]
path = [
    ".gitignore",
    "images/khronos_logo.png",
    "images/vulkan_logo.png",
    "chapters/**.md",
    "chapters/**.png",
    "chapters/**.svg",
    "chapters/slang-write-once-run-anywhere-graphic.webp",
]
SPDX-FileCopyrightText = "2026 The Khronos Group, Inc."
SPDX-License-Identifier = "CC-BY-4.0"
