// Copyright 2021-2022 The Khronos Group, Inc.
// SPDX-License-Identifier: CC-BY-4.0

ifndef::chapters[:chapters:]

[[formats]]
= フォーマット

Vulkan のフォーマットは、メモリのレイアウトを記述するために使用されます。この章では、Vulkan のフォーマットのバリエーションに関する概要と、それらを使用する方法に関する情報を提供します。詳細は、link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#formats[Vulkan Spec フォーマット章] と link:https://www.khronos.org/registry/DataFormat/specs/1.3/dataformat.1.3.html[Khronos Data Format Specification] の両方に明記されています。

`VkFormat` の最も一般的な使用例は、`VkImage` を作成する場合です。`VkFormat` はうまく定義されているため、`VkBufferView` 、xref:{chapters}vertex_input_data_processing.adoc#input-attribute-format[頂点入力属性]、link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#spirvenv-image-formats[SPIR-V イメージフォーマットのマッピング]、link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureGeometryTrianglesDataKHR.html[ボトムレベル高速化構造での三角形ジオメトリ作成]などのためのメモリレイアウトを記述する場合にも使用されます。

[[feature-support]]
== 機能の対応

「フォーマットの対応」は、フォーマットごとに単一のバイナリ値ではなく、各フォーマットが link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFormatFeatureFlagBits.html[VkFormatFeatureFlagBits] のセットを持ち、それぞれがそのフォーマットでサポートされている機能を記述していることが重要です。

サポートされるフォーマットは実装によって異なる可能性がありますが、link:https://www.khronos.org/registry/vulkan/specs/1.3/html/vkspec.html#features-required-format-support[フォーマット機能の最小セットは保証]されています。アプリケーションは、サポートされているフォーマットのプロパティをlink:https://www.khronos.org/registry/vulkan/specs/1.3/html/vkspec.html#formats-properties[クエリ]することができます。

[NOTE]
====
link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_get_physical_device_properties2.html[VK_KHR_get_physical_device_properties2] と link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_format_feature_flags2.html[VK_KHR_format_feature_flags2] は共に、フォーマット機能をクエリするための別の方法を公開します。
====

=== フォーマット機能をクエリする例

この例は、`VK_FORMAT_R8_UNORM` フォーマットが `VkImageCreateInfo::tiling` 用に `VK_IMAGE_TILING_LINEAR` で作成した `VkImage` からのサンプリングをサポートしているかどうかを確認するコードです。これを行うために、`VK_FORMAT_R8_UNORM` の `linearTilingFeatures` フラグをクエリし、 `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` が実装によりサポートされているかどうかを確認します。

[source,cpp]
----
// Vulkan 1.0コアを使用
VkFormatProperties formatProperties;
vkGetPhysicalDeviceFormatProperties(physicalDevice, VK_FORMAT_R8_UNORM, &formatProperties);
if ((formatProperties.linearTilingFeatures & VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT) != 0) {
    // 対応している
} else {
    // 対応していない
}
----

[source,cpp]
----
// Vulkan 1.0コアまたはVK_KHR_get_physical_device_properties2 を使用
VkFormatProperties2 formatProperties2;
formatProperties2.sType = VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2;
formatProperties2.pNext = nullptr; // 拡張機能のために使用される

vkGetPhysicalDeviceFormatProperties2(physicalDevice, VK_FORMAT_R8_UNORM, &formatProperties2);
if ((formatProperties2.formatProperties.linearTilingFeatures & VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT) != 0) {
    // 対応している
} else {
    // 対応していない
}
----

[source,cpp]
----
// VK_KHR_format_feature_flags2 を使用
VkFormatProperties3KHR formatProperties3;
formatProperties3.sType = VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_3_KHR;
formatProperties3.pNext = nullptr;

VkFormatProperties2 formatProperties2;
formatProperties2.sType = VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2;
formatProperties2.pNext = &formatProperties3;

vkGetPhysicalDeviceFormatProperties2(physicalDevice, VK_FORMAT_R8_UNORM, &formatProperties2);
if ((formatProperties3.linearTilingFeatures & VK_FORMAT_FEATURE_2_STORAGE_IMAGE_BIT_KHR) != 0) {
    // 対応している
} else {
    // 対応していない
}
----

== フォーマットのバリエーション

フォーマットには多くのバリエーションがあり、ほとんどは link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#_identification_of_formats[フォーマットの名前]でグループ化されています。イメージを扱う場合、link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageAspectFlagBits.html[VkImageAspectFlagBits] 値は、クリアやコピーなどの操作のために、データのどの部分にアクセスするかを表すために使用されます。

=== 色

`R`、`G`、`B` または `A` 成分を持つフォーマットで、 `VK_IMAGE_ASPECT_COLOR_BIT` でアクセスします。

=== 深度とステンシル

`D` または `S` 成分を持つフォーマットです。これらのフォーマットはlink:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#formats-depth-stencil[不透明とみなされ]、深度/ステンシルイメージとのlink:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VkBufferImageCopy[コピー]に関して特別なルールがあります。

いくつかのフォーマットは、深度成分とステンシル成分の両方を持ち、 `VK_IMAGE_ASPECT_DEPTH_BIT` と `VK_IMAGE_ASPECT_STENCIL_BIT` で別々にアクセスできます。

[NOTE]
====
Vulkan 1.2 で昇格した link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_separate_depth_stencil_layouts.html[VK_KHR_separate_depth_stencil_layouts] と link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_separate_stencil_usage.html[VK_EXT_separate_stencil_usage] を使用すると、深度とステンシル成分間でより細かく制御できるようになります。
====

深度フォーマットについての詳しい情報は、xref:{chapters}depth.adoc#depth-formats[深度の章]にあります。

=== 圧縮

link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#compressed_image_formats[圧縮イメージ]は、1つの領域内に複数の画素を相互依存的にエンコードして表現する形式です。


.Vulkan 圧縮イメージフォーマット
[options="header"]
|===
|フォーマット|有効化方法
|link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#appendix-compressedtex-bc[BC (Block-Compressed)] |`VkPhysicalDeviceFeatures::textureCompressionBC`
|link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#appendix-compressedtex-etc2[ETC2 and EAC] |`VkPhysicalDeviceFeatures::textureCompressionETC2`
|link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#appendix-compressedtex-astc[ASTC LDR] |`VkPhysicalDeviceFeatures::textureCompressionASTC_LDR`
|link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#appendix-compressedtex-astc[ASTC HDR] |link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_texture_compression_astc_hdr.html[VK_EXT_texture_compression_astc_hdr]
|link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#appendix-compressedtex-pvrtc[PVRTC] | link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_IMG_format_pvrtc.html[VK_IMG_format_pvrtc]
|===

=== 平面

link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html[VK_KHR_sampler_ycbcr_conversion] と link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_ycbcr_2plane_444_formats.html[VK_EXT_ycbcr_2plane_444_formats] は xref:{chapters}VK_KHR_sampler_ycbcr_conversion.adoc#multi-planar-formats[multi-planar フォーマット] を Vulkan に追加しました。
`VK_IMAGE_ASPECT_PLANE_0_BIT`、`VK_IMAGE_ASPECT_PLANE_1_BIT`、`VK_IMAGE_ASPECT_PLANE_2_BIT` で平面に個別にアクセスできます。

=== パック

link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#formats-packed[パックされたフォーマット]は、アドレスアライメントを目的としたものです。例として、`VK_FORMAT_A8B8G8R8_UNORM_PACK32` と `VK_FORMAT_R8G8B8A8_UNORM` は非常に似ていますが、仕様の link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#fxvertex-input-extraction[Vertex Input Extraction セクション]の数式を使用すると、以下のようになります。

____
attribAddress = bufferBindingAddress + vertexOffset + attribDesc.offset;
____

`VK_FORMAT_R8G8B8A8_UNORM` では `attribAddress` はコンポーネントサイズ (8 bits) の倍数でなければならず、`VK_FORMAT_A8B8G8R8_UNORM_PACK32` ではパックサイズ (32 bits) の倍数である必要があります。

=== 外部

現在、`VK_ANDROID_external_memory_android_hardware_buffer` 拡張機能でのみサポートされています。この拡張機能を使うと、Android アプリケーションが実装で定義された外部フォーマットをインポートし、 xref:{chapters}VK_KHR_sampler_ycbcr_conversion.adoc[VkSamplerYcbcrConversion] で使用できるようになります。これらの外部フォーマットで許可されるものには多くの制限があり、link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#memory-external-android-hardware-buffer-external-formats[仕様に記載]されています。
