// Copyright 2019-2022 The Khronos Group, Inc.
// SPDX-License-Identifier: CC-BY-4.0

ifndef::chapters[:chapters:]

[[layers]]
= レイヤ

レイヤは、Vulkan システムを補強するオプション要素です。レイヤは、アプリケーションからハードウェアに至るまで、既存の Vulkan 関数をインターセプトし、評価し、修正することができます。レイヤのプロパティは、アプリケーションから link:https://docs.vulkan.org/spec/latest/chapters/extensions.html#vkEnumerateInstanceLayerProperties[vkEnumerateInstanceLayerProperties] でクエリできます。

== レイヤの使い方

レイヤは共有ライブラリとしてパッケージ化されており、ローダによって動的に読み込まれ、ローダとアプリケーションの間に挿入されます。レイヤを使用するために必要なのは、バイナリファイルの場所と、どのレイヤを有効にするかという2点です。使用するレイヤには、アプリケーションが明示的に使用するものと、ローダに指示して暗黙的に使用するものがあります。暗黙的なレイヤと明示的なレイヤの詳細については、link:https://github.com/KhronosGroup/Vulkan-Loader/blob/main/loader/LoaderAndLayerInterface.md#implicit-vs-explicit-layers[ローダとレイヤのインターフェイス]を参照してください。

link:https://vulkan.lunarg.com/sdk/home[Vulkan SDK] には、各プラットフォームでのレイヤの検出と設定方法に特化したlink:https://vulkan.lunarg.com/doc/sdk/latest/windows/layer_configuration.html[レイヤ設定ドキュメント]が含まれています。

== Vulkan Configurator ツール

Windows、Linux、macOS の開発者は、Vulkan Configurator（vkconfig）を使用して、GUI から明示的なレイヤの有効化、暗黙的なレイヤの無効化、およびレイヤ設定の変更を行うことができます。Vulkan Configurator の使用に関する詳細は、Vulkan SDK の link:https://vulkan.lunarg.com/doc/sdk/latest/windows/vkconfig.html[Vulkan Configurator ドキュメント]を参照してください。

== デバイスレイヤの非推奨化

かつてはインスタンスレイヤとデバイスレイヤの両方がありましたが、デバイスレイヤは Vulkan の初期段階でlink:https://docs.vulkan.org/spec/latest/chapters/extensions.html#extendingvulkan-layers-devicelayerdeprecation[非推奨]となっているため、避けてください。

== レイヤの作成

ローダとレイヤが相互に通信することに同意する方法であるlink:https://github.com/KhronosGroup/Vulkan-Loader/blob/main/loader/LoaderAndLayerInterface.md#loader-and-layer-interface[ローダからレイヤへのインターフェイス]に従う限り、誰でもレイヤを作成することができます。

== プラットフォームのバリエーション

暗黙的にレイヤを読み込む方法は、ローダやプラットフォームによって異なります。

=== Android

Android P（Android 9 / APIレベル28）では、デバイスがデバッグ可能な状態にあり、`getprop ro.debuggable` がlink:http://androidxref.com/9.0.0_r3/xref/frameworks/native/vulkan/libvulkan/layers_extensions.cpp#454[1を返した場合]、ローダは link:http://androidxref.com/9.0.0_r3/xref/frameworks/native/vulkan/libvulkan/layers_extensions.cpp#67[/data/local/debug/vulkan] を検索します。

Android P (Android 9 / API level 28)からは、アプリケーションがデバッグモードでビルドされている場合、link:https://developer.android.com/ndk/guides/graphics/validation-layer#vl-adb[ADB] を使って暗黙のレイヤをプッシュできるようになりました。

暗黙的なレイヤを使用するには、上記のオプション以外に方法はありません。

=== Linux

link:https://vulkan.lunarg.com/doc/sdk/latest/linux/layer_configuration.html[Vulkan SDK] では、Linux で暗黙のレイヤを使用する方法が説明されています。

=== MacOS

link:https://vulkan.lunarg.com/doc/sdk/latest/mac/layer_configuration.html[Vulkan SDK] では、MacOS で暗黙のレイヤを使用する方法が説明されています。

=== Windows

link:https://vulkan.lunarg.com/doc/sdk/latest/windows/layer_configuration.html[Vulkan SDK] では、Windows で暗黙のレイヤを使用する方法が説明されています。
