// Copyright 2019-2022 The Khronos Group, Inc.
// SPDX-License-Identifier: CC-BY-4.0

// Required for both single-page and combined guide xrefs to work
ifndef::chapters[:chapters:]

[[querying-extensions-features]]
= Querying Properties, Extensions, Features, Limits, and Formats

One of Vulkan's main features is that is can be used to develop on multiple platforms and devices. To make this possible, an application is responsible for querying the information from each physical device and then basing decisions on this information.

The items that can be queried from a physical device

  * Properties
  * Features
  * Extensions
  * Limits
  * Formats

== Properties

There are many other components in Vulkan that are labeled as properties. The term "`properties`" is an umbrella term for any read-only data that can be queried.

== Extensions

[NOTE]
====
Check out the xref:{chapters}enabling_extensions.adoc#enabling-extensions[Enabling Extensions] chapter for more information.

There is a link:https://www.khronos.org/registry/vulkan/#repo-docs[Registry] with all available extensions.
====

There are many times when a set of new functionality is desired in Vulkan that doesn't currently exist. Extensions have the ability to add new functionality. Extensions may define new Vulkan functions, enums, structs, or feature bits. While all of these extended items are found by default in the Vulkan Headers, it is **undefined behavior** to use extended Vulkan if the xref:{chapters}enabling_extensions.adoc#enabling-extensions[extensions are not enabled].

== Features

[NOTE]
====
Checkout the xref:{chapters}enabling_features.adoc#enabling-features[Enabling Features] chapter for more information.
====

Features describe functionality which is not supported on all implementations. Features can be link:https://www.khronos.org/registry/vulkan/specs/1.3/html/vkspec.html#vkGetPhysicalDeviceFeatures[queried] and then enabled when creating the `VkDevice`. Besides the link:https://www.khronos.org/registry/vulkan/specs/1.3/html/vkspec.html#features[list of all features], some link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#features-requirements[features are mandatory] due to newer Vulkan versions or use of extensions.

A common technique is for an extension to expose a new struct that can be passed through `pNext` that adds more features to be queried.

== Limits

Limits are implementation-dependent minimums, maximums, and other device characteristics that an application may need to be aware of. Besides the link:https://www.khronos.org/registry/vulkan/specs/1.3/html/vkspec.html#limits[list of all limits], some limits also have link:https://www.khronos.org/registry/vulkan/specs/1.3/html/vkspec.html#limits-minmax[minimum/maximum required values] guaranteed from a Vulkan implementation.

== Formats

Vulkan provides many `VkFormat` that have multiple `VkFormatFeatureFlags` each holding a various link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFormatFeatureFlagBits.html[VkFormatFeatureFlagBits] bitmasks that can be queried.

Checkout the xref:{chapters}formats.adoc#feature-support[Format chapter] for more information.

== Tools

There are a few tools to help with getting all the information in a quick and in a human readable format.

`vulkaninfo` is a command line utility for Windows, Linux, and macOS that enables you to see all the available items listed above about your GPU. Refer to the link:https://vulkan.lunarg.com/doc/sdk/latest/windows/vulkaninfo.html[Vulkaninfo documentation] in the Vulkan SDK.

The link:https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer&hl=en_US[Vulkan Hardware Capability Viewer] app developed by Sascha Willems, is an Android app to display all details for devices that support Vulkan.
