// Copyright 2026 The Khronos Group, Inc.
// SPDX-License-Identifier: CC-BY-4.0

ifndef::chapters[:chapters:]
ifndef::images[:images: images/]

[[slang-in-vulkan]]
= Slang in Vulkan

Slang is a _pleasing description TBD_ shading language that can be used with
Vulkan by compiling Slang shaders to SPIR-V.

== _TBD_

_This page was generated by copying and simplifying the xref:hlsl.adoc[HLSL]
page.
All the Slang-specific details we care about need to be filled in._

[[slang-educational-resources]]
== Educational resources

If you are new to Slang, a good starting point is...

[[slang-applications-pov]]
== From the application's point-of-view

From the application's point-of-view, using Slang is exactly the same as
using GLSL.
As the application always consumes shaders in the SPIR-V format, the only
difference is in the tooling to generate SPIR-V shaders from the desired
shading language.

[[slang-spirv-mapping-manual]]
== Slang to SPIR-V feature mapping manual

A great starting point on using Slang in Vulkan via SPIR-V is _TBD_.

== Other Sections _TBD_

_Add additional material similar to the HLSL page, e.g. Syntax comparison,
the Slang compiler, where to get Slang downloads and documentation..._
