// Copyright 2019-2025 The Khronos Group, Inc.
// SPDX-License-Identifier: CC-BY-4.0

// Required for both single-page and combined guide xrefs to work
ifndef::chapters[:chapters:]
ifndef::images[:images: images/]

[[vulkan-spec]]
= Vulkan Specification

The Vulkan Specification (usually referred to as the _Vulkan Spec_) is the official description of how the Vulkan API works and is ultimately used to decide what is and is not valid Vulkan usage. At first glance, the Vulkan Spec seems like an incredibly huge and dry chunk of text, but it is usually the most useful item to have open when developing.

[NOTE]
====
Reference the Vulkan Spec early and often.
====

== Vulkan Spec Variations

The Vulkan Spec can be built for any version and with any permutation of extensions. The Khronos Group hosts the link:https://registry.khronos.org/vulkan/specs/[Vulkan Spec Registry] which contains a few publicly available variations that most developers will find sufficient. Anyone can build their own variation of the Vulkan Spec from link:https://github.com/KhronosGroup/Vulkan-Docs/blob/main/BUILD.adoc[Vulkan-Docs].

When building the Vulkan Spec, you pass in what version of Vulkan to build for as well as what extensions to include. A Vulkan Spec without any extensions is also referred to as the link:https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#extendingvulkan-coreversions[core version] as it is the minimal amount of Vulkan an implementation needs to support in order to be xref:{chapters}vulkan_cts.adoc#vulkan-cts[conformant].

== Vulkan Spec Version

Vulkan 1.0 to 1.3, there was a dedicated version of the spec. To to reduce build permutation, starting with Vulkan 1.4 there is now a `latest` version that will always be updated to the latest version of Vulkan.

The link:https://vulkan.lunarg.com/doc/sdk/1.4.304.0/windows/1.4-extensions/vkspec.html[Vulkan SDK] will always contain the version of the spec that it was created with.

== Vulkan Spec Format

The Vulkan Spec can be built into different formats.

=== Antora

To both combine various resources and improve navigation, there is now an link:https://docs.vulkan.org/spec/latest/index.html[Antora built version of the spec] that is recommanded to use.

=== HTML

If you want to view the Vulkan Spec in its entirety as HTML, you just need to view the `html/vkspec.html` file.

https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html

The Vulkan SDK comes packaged with Vulkan Spec in its entirety as HTML for the version corresponding to the Vulkan SDK version. (https://vulkan.lunarg.com/doc/sdk/1.4.304.0/windows/1.4-extensions/vkspec.html)

=== PDF

To view the PDF format, visit the `pdf/vkspec.pdf` file.

https://registry.khronos.org/vulkan/specs/latest/pdf/vkspec.pdf

The Vulkan SDK also comes with a PDF version (https://vulkan.lunarg.com/doc/sdk/1.4.304.0/windows/1.4-extensions/vkspec.pdf)

=== Man pages

The Khronos Group currently only host the Vulkan Man Pages for the latest version of the spec, with all extensions, on the link:https://registry.khronos.org/vulkan/specs/latest/man/html/[online registry].

The Vulkan Man Pages can also be found in the VulkanSDK for each SDK version. See the link:https://vulkan.lunarg.com/doc/sdk/latest/windows/apispec.html[Man Pages] for the latest Vulkan SDK.
