// Copyright 2019-2025 The Khronos Group, Inc.
// SPDX-License-Identifier: CC-BY-4.0

// Required for both single-page and combined guide xrefs to work
ifndef::chapters[:chapters:]
ifndef::images[:images: images/]

[[vulkan-spec]]
= Vulkan Specification

Vulkan Specification(Vulkan 사양서, 통상 _Vulkan Spec_ 이라고 함)은 Vulkan API의 작동 방식에 대한 공식적인 설명이며, 궁극적으로 무엇이 유효한 Vulkan 사용법인지 아닌지를 결정하는 데 사용됩니다. 언뜻 보기에 Vulkan 사양서는 엄청나게 방대하고 무미건조한 텍스트 덩어리처럼 보이지만, 보통 개발할 때 열어두면 가장 유용한 자료입니다.

[NOTE]
====
Vulkan 사양서를 일찍, 그리고 자주 참조하세요.
====

== Vulkan Spec 변화

Vulkan Spec은 모든 버전과 모든 확장 기능 조합을 사용하여 빌드할 수 있습니다. 크로노스 그룹은 link:https://registry.khronos.org/vulkan/specs/[Vulkan Spec Registry]를 호스트하고 있으며, 대부분의 개발자에게 충분한 변형이 공개되어 있습니다. 누구나 link:https://github.com/KhronosGroup/Vulkan-Docs/blob/main/BUILD.adoc[Vulkan-Docs]에서 자신만의 Vulkan Spec 변형을 만들 수 있습니다.

Vulkan Spec을 빌드할 때, 어떤 버전용인지, 어떤 확장 기능을 포함할지 지정합니다. 확장 기능이 없는 Vulkan Spen을 link:https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#extendingvulkan-coreversions[core version]이라고도 하는데, 이는 구현이 xref:{chapters}vulkan_cts.adoc#vulkan-cts[호환]되기 위해 지원해야 하는 최소한의 Vulkan이 됩니다.

== Vulkan Spec 버전

Vulkan 1.0에서 1.3까지는 전용 버전의 Spec이 있었습니다. 빌드 순열을 줄이기 위해 Vulkan 1.4부터는 항상 최신 버전의 Vulkan으로 업데이트되는 '최신' 버전이 있습니다.

링크: https://vulkan.lunarg.com/doc/sdk/1.4.304.0/windows/1.4-extensions/vkspec.html[Vulkan SDK]에는 항상 생성된 Spec 버전이 포함됩니다.

== Vulkan Spec 포맷

Vulkan Spec은 다양한 포맷으로 빌드할 수 있습니다.

=== Antora

다양한 리소스를 결합하고 탐색을 개선하기 위해 이제 링크:https://docs.vulkan.org/spec/latest/index.html[Antora 빌드 Spec 버전]을 사용할 것을 권장합니다.

=== HTML

Vulkan Spec 전체를 HTML로 보려면 `html/vkspec.html` 파일을 보기만 하면 됩니다.

https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html

벌칸 SDK는 해당 버전에 해당하는 벌칸 스펙 전체가 HTML로 패키징되어 제공됩니다. (https://vulkan.lunarg.com/doc/sdk/1.4.304.0/windows/1.4-extensions/vkspec.html)

Vulkan SDK는 Vulkan Spec 전체가 Vulkan SDK 버전에 해당하는 버전의 HTML로 패키징되어 제공됩니다. 최신 Vulkan SDK는 (https://vulkan.lunarg.com/doc/sdk/1.4.304.0/windows/1.4-extensions/vkspec.html)

=== PDF

PDF 포맷은 `pdf/vkspec.pdf` 파일을 보세요.

https://registry.khronos.org/vulkan/specs/latest/pdf/vkspec.pdf

Vulkan SDK는 PDF 버전도 함께 제공됩니다(https://vulkan.lunarg.com/doc/sdk/1.4.304.0/windows/1.4-extensions/vkspec.pdf).

=== Man pages

크로노스 그룹은 현재 link:https://registry.khronos.org/vulkan/specs/latest/man/html/[온라인 레지스트리]에서 모든 확장 기능을 포함한 최신 버전의 사양에 대한 Vulkan Man Pages만 호스팅 하고 있습니다.

Vulkan Man Pages는 각 SDK 버전에 대한 Vulkan SDK에서도 확인할 수 있습니다. 최신 Vulkan SDK는 link:https://vulkan.lunarg.com/doc/sdk/latest/windows/apispec.html[Man Pages]를 참조하세요.
